### PR TITLE
fixed all the css changes and bugs highlighted

### PR DESCRIPTION
**Pull request by kevinfwl**
Below highlights the fixes for this PR

css fixes
- changed course cards from deletion btn from circle -> x
- Make search bar ghostwhite background 
- search bar for courses doesn't align properly
- tags should be centred 

ipad css fixes
- Ipad columns for terms expand (now, the add course btn and garbage can is displayed on all mobile devices because there is no point of hovering)
- scrolling leads to the checklist page

### CODE REVIEW

**Review by haowei99 — DISMISSED** [review]

**Review by CalderLund — CHANGES_REQUESTED** [review]
I think that the Course Code on the Card needs larger text. Idk why you made it smaller. It is too hard to read on smaller screens. Should be same size as before. Maybe shrink tags to reduce card space.

**Comment by kevinfwl** [comment]
The reason why I made the text smaller is to fix the following bug:
* search bar for courses doesn't align properly

I am not entirely sure if there is a trivial way to do it otherwise

**Comment by haowei99** [comment]
> The reason why I made the text smaller is to fix the following bug:
> 
> * search bar for courses doesn't align properly
> 
> I am not entirely sure if there is a trivial way to do it otherwise since this is a problem with vuetify

I think it's fine tbh

**Comment by CalderLund** [comment]
@kevinfwl what search bar?

**Review by haowei99 — COMMENTED** [review]
@CalderLund @kevinfwl Fixed width problem without changing font size

**Review by CalderLund — CHANGES_REQUESTED** [review]
The search bar on home page expands past the width of the bar. 

No longer experience issue of it changing sizes while scrolling. Now it is just not matched size by default.

**Comment by CalderLund** [comment]
I think that the solution should be cutting off the text rather than expanding the area.

**Review by CalderLund — APPROVED** [review]
Issues are fixed.
lgtm

**Pull request merged**
