### PR TITLE
Css figma

### PR DESCRIPTION
**Pull request by CalderLund**

### CODE REVIEW

**Comment by haowei99** [comment]
@CalderLund  Please check out the branch and make sure your laptop can load this properly

**Comment by CalderLund** [comment]
Found multiple problems:
- I find it hard to read the Major Requirements dropdown text (should be larger)
- Refresh button should be larger and moved to the right of the container
- When selecting a course from a choice of courses, the bold on hover is no longer there, making it hard to tell that you can click between courses

**Comment by CalderLund** [comment]
@haowei99

**Comment by kevinfwl** [comment]
@CalderLund Let me know if this is fixed
Still working on two things:
1. the download button should directly download the file 
2. when displaying in iPad, the margins for the alert button is not properly tuned

**Comment by CalderLund** [comment]
In addition to what you mentioned @kevinfwl , the Contact Us page CSS needs to be adjusted accordingly as well. It looks weird clicking on it as is.

**Review by haowei99 — COMMENTED** [review]
@kevinfwl I will let you finished the rest of the css then

**Review by haowei99 — APPROVED** [review]
lgtm

**Comment by CalderLund** [comment]
Still needs updated Contact Us page. @kevinfwl

**Comment by kevinfwl** [comment]
@CalderLund The contact us page is updated tho. See commit 
634cde1

**Comment by CalderLund** [comment]
Colour scheme doesn't match. It looks like New CSS + Old Contact Page

**Comment by CalderLund** [comment]
@kevinfwl

**Comment by haowei99** [comment]
image
The degree req is a bit too big, it's the same font as the degree title

**Pull request merged**
