### PR TITLE
Bug patches

### PR DESCRIPTION
**Pull request by AdrianSantoPasqualini**
Minor Changes

### CODE REVIEW

**Review by haowei99 — APPROVED** [review]

**Review by haowei99 — COMMENTED** [review]
I fixed the bug that solve the problem where cards show up in correctly if dragged around. It relies on the fact that this.allCourseChoices is updated. If you try and swap a choose x course with another course (CS 135 for ex) and then try to select the choose x, it breaks. 

Refer to line 145: RequirementOptionsModal.vue

**Review by haowei99 — CHANGES_REQUESTED** [review]
I fixed the bug that solve the problem where cards show up in correctly if dragged around. It relies on the fact that this.allCourseChoices is updated. If you try and swap a choose x course with another course (CS 135 for ex) and then try to select the choose x, it breaks.

Refer to line 145: RequirementOptionsModal.vue

**Review by haowei99 — COMMENTED** [review]
Also remember to comment out backend_url

**Comment by CalderLund** [comment]
Can confirm. Found same bug as Hao Wei.

**Comment by CalderLund** [comment]
Why are English reqs showing up in 100s?

**Comment by CalderLund** [comment]
Excel spreadsheet download works

**Comment by CalderLund** [comment]
NON-MATH seems to include CS and MATBUS. Maybe more.

**Comment by CalderLund** [comment]
In Major, course ranges (i.e. CS 400-499) exist, but when in minor (I used CO minor), ranges do not appear.

**Comment by AdrianSantoPasqualini** [comment]
> I fixed the bug that solve the problem where cards show up in correctly if dragged around. It relies on the fact that this.allCourseChoices is updated. If you try and swap a choose x course with another course (CS 135 for ex) and then try to select the choose x, it breaks.
> 
> Refer to line 145: RequirementOptionsModal.vue

I found the underlying cause and fixed it

**Comment by AdrianSantoPasqualini** [comment]
> NON-MATH seems to include CS and MATBUS. Maybe more.

This is actually a backend bug it seems, the list of math courses is incomplete which causes extra non-math courses to get shown
`if code == "MATH": code = "ACTSC, AMATH, CO, MATH, PMATH, STAT"`
On line 35 of course_view.py

**Comment by AdrianSantoPasqualini** [comment]
Closed by accident, reopening.

**Comment by AdrianSantoPasqualini** [comment]
> Why are English reqs showing up in 100s?

Good catch, there was an issue with initializing the year for the requirements

**Comment by AdrianSantoPasqualini** [comment]
> In Major, course ranges (i.e. CS 400-499) exist, but when in minor (I used CO minor), ranges do not appear.

This was also caused by the incorrect year initialization. The range was being put into the 300s section instead of other.

**Comment by AdrianSantoPasqualini** [comment]
> Also remember to comment out backend_url

Since Calder has another PR streamlining the backend_api url I will leave this as is

**Review by CalderLund — APPROVED** [review]
LGTM

**Review by haowei99 — APPROVED** [review]
lgtm

**Pull request merged**
