### PR TITLE
User authentication

### PR DESCRIPTION
**Pull request by AdrianSantoPasqualini**
- Adds user authentication via Google to save plans

### CODE REVIEW

**Comment by kevinfwl** [comment]
Some comments, otherwise LGTM:

- When I select a new program after logging in, it doesn't save the program until I start dragging courses from that program into the terms. 
    Steps to recreate:
    1. Login
    2. Select "applied mathematics" from landing page
    3. Drag 1 card from "applied mathematics"
    4. Go back to landing page and select "global business and digital arts"
    5. logout
    6. Log back in (and you should see "applied mathematics" and the 1 card that is dragged)

  Was wondering if this is the expected behaviour. 

- signing in will override all the course selections that are done before sign in, we should have a warning or notif somewhere to let users know.
- changing the button to have a google symbol might be clearer (e.g. similar to the pic below)
Capture

**Review by kevinfwl — COMMENTED** [review]
Some comments, otherwise LGTM:

- When I select a new program after logging in, it doesn't save the program until I start dragging courses from that program into the terms. 
    Steps to recreate:
    1. Login
    2. Select "applied mathematics" from landing page
    3. Drag 1 card from "applied mathematics"
    4. Go back to landing page and select "global business and digital arts"
    5. logout
    6. Log back in (and you should see "applied mathematics" and the 1 card that is dragged)

  Was wondering if this is the expected behaviour. 

- signing in will override all the course selections that are done before sign in, we should have a warning or notif somewhere to let users know.
- changing the button to have a google symbol might be clearer (e.g. similar to the pic below)
Capture

**Review by haowei99 — CHANGES_REQUESTED** [review]
I have some design suggestions:
image
I think this button should be aligned to the course table. Can you make the button a bit smaller so it stays a bit more consistent with the Contact and About tab (It looks a bit too big next to them)

Also, please change the name to UWPath here: 
image

Bug wise:
- I have a problem loading major when logging back in:
1. Choose major and drag course
2. Sign in
3. Then sign out and change to a diff major 
4. Then sign in again 
5. I don't see my major change

- When I refresh localhost it brings me to course selection page -> I'm not sure if this is a problem of my localhost or the logic to bring page to course selection after login breaks it?

**Comment by haowei99** [comment]
Good job overall! I think it is looking good!

**Comment by AdrianSantoPasqualini** [comment]
> Some comments, otherwise LGTM:
> 
> * When I select a new program after logging in, it doesn't save the program until I start dragging courses from that program into the terms.
>   Steps to recreate:
>   
>   1. Login
>   2. Select "applied mathematics" from landing page
>   3. Drag 1 card from "applied mathematics"
>   4. Go back to landing page and select "global business and digital arts"
>   5. logout
>   6. Log back in (and you should see "applied mathematics" and the 1 card that is dragged)
>   
>   Was wondering if this is the expected behaviour.
> * signing in will override all the course selections that are done before sign in, we should have a warning or notif somewhere to let users know.
> * changing the button to have a google symbol might be clearer (e.g. similar to the pic below)
>   Capture

- I cannot replicate the first bug (see video)
- A modal should pop up if the plan on your account is different than your local changes to ask which one you want to keep
- Yeah I can look into adding the symbol

**Comment by AdrianSantoPasqualini** [comment]
> I have some design suggestions:
> image
> I think this button should be aligned to the course table. Can you make the button a bit smaller so it stays a bit more consistent with the Contact and About tab (It looks a bit too big next to them)
> 

Yeah Ill try to make it more consistent

> Also, please change the name to UWPath here:
> image
> 

This is actually a little difficult to do. We would need to do some domain verification and a bunch of other stuff with google.

> Bug wise:
> 
> * I have a problem loading major when logging back in:
> 
> 1. Choose major and drag course
> 2. Sign in
> 3. Then sign out and change to a diff major
> 4. Then sign in again
> 5. I don't see my major change
> 

Similar to Kevin's bug, I cannot replicate this

> * When I refresh localhost it brings me to course selection page -> I'm not sure if this is a problem of my localhost or the logic to bring page to course selection after login breaks it?

This was a change I added to make the flow less confusing. Essentially, if the user has a plan already set up, then the landing page will take them straight to course selection, rather than them having to find and click Plan Courses (Which is a bit out of the way) or potentially overwriting their plan by choosing a new one.

**Comment by haowei99** [comment]
For the refresh button: when I first enter uwpath.live, it still left me with homepage (unless I refresh). Would this be confusing for people as it is not intuitive. Do you think it would be better if we add the Go to plan courses (with link) to the popup that says `A major was selected in the past, do you wish to overwrite?`

**Comment by haowei99** [comment]
Found one more bug: 

Once you load from the account -> Go to add plan -> No data available for both Minors and options (until you change the major again)

**Review by haowei99 — CHANGES_REQUESTED** [review]
Backend bugs seem to be resolved. Have a few more comments:

- Noticed one thing: if you sign out, stay on the same program, and check a few more options from the checklist, then sign back in - it wouldn't prompt the "stay with the current setting or not". I assume it is based on how many courses are dragged in, and state of it. This is an edge edge case, I'm indifferent to leave it this way, but just want to bring it up

- CSS Problems (critical): Doesn't display properly on Ipad, or if I slightly make the window size smaller, I have a 13" laptop. The button just disappears (unlike how it shrinks like what we have in Prod). Some CSS work needs to be done here. I am down to change it to just "Login" and shrink the button smaller length wise. We could also remove words and then have a subscript "Sign in to Save" when hovered around. But I think the main part is that the button disappears on ipad or on shrink. 
- Personal pref: I think the button is still too big and it bothers me a bit. Should we make it to the same size as "Add a major,minor.." button? @kevinfwl  @b47huang

**Review by haowei99 — APPROVED** [review]

**Pull request merged**
