### PR TITLE
add year selection for pick courses

### PR DESCRIPTION
**Pull request by kevinfwl**
@haowei99 PTAL. Also, can you add some animation transitions to the autocomplete boxes on landingpage.vue if possible?

### CODE REVIEW

**Comment by haowei99** [comment]
Do we cache academic year? The academic year state disappears if you refreshed from the course table page. Otherwise the rest is implemented properly

**Comment by haowei99** [comment]
I see that line 143  `this.setAcademicYear(this.selectedYear);` is setting the state under LandingPage.vue. But I think we need this in the cache. @CalderLund  do you rmb how to do this?

**Comment by haowei99** [comment]
I think year should be stored in class ProgramInfo

**Comment by kevinfwl** [comment]
> I think year should be stored in class ProgramInfo

I thought of that originally but then you cant use it to query the requirements in "fetchrequirements" cuz they are in different modules

**Comment by kevinfwl** [comment]
> I see that line 143 `this.setAcademicYear(this.selectedYear);` is setting the state under LandingPage.vue. But I think we need this in the cache. @CalderLund do you rmb how to do this?

Right, I forgot about that, when you get to that @CalderLund can u walk me through how to do caching, just for stuff down the line.

**Comment by haowei99** [comment]
I think I figured it out. I have removed the academic year state. I also updated backend to allow it to return year attribute so you should pull backend to test this. Year will be saved in program_info which is saved through cache. 

Refreshing now will show the year on the info box in Add a minor as well as checklist footer section.

Please help me test this and see if it works (refresh the page whenever, change programs from both home page and Add a minor, option box)

**Review by CalderLund — APPROVED** [review]
lgtm

**Pull request merged**
