### PR TITLE
Update checklist to credits

### PR DESCRIPTION
**Pull request by AdrianSantoPasqualini**

### CODE REVIEW

**Review by CalderLund — CHANGES_REQUESTED** [review]
I tested with "Biomedical Sciences" as the major and dragged over "BIOL 130" and "BIOL 130L". Only "BIOL 130" was checked-off in the checklist. "BIOL 130L" was not.

**Review by haowei99 — CHANGES_REQUESTED** [review]
In BCS, Non-math dragged to the table does not tick the non-math requirement

**Review by haowei99 — COMMENTED** [review]
Should work for SCIENCE (in Honours Science and Aviation) and LANGUAGE (in Global Business and Digital Arts)

**Review by haowei99 — COMMENTED** [review]
Need to work for LANUGAGE courses too (Global business and digital arts)

**Review by haowei99 — APPROVED** [review]
LGTM. Resolve Merge conflict before merge into master

**Review by haowei99 — APPROVED** [review]

**Review by CalderLund — APPROVED** [review]

**Pull request merged**
