### PR TITLE
Beta CSS Changes

### PR DESCRIPTION
**Pull request by AdrianSantoPasqualini**

### CODE REVIEW

**Review by CalderLund — CHANGES_REQUESTED** [review]
The course plan page and the checklist seem to have different widths. They should be the same.

**Comment by CalderLund** [comment]
Also, if you can, please update the AddCourseCard modal stuff to match the regular modal.

**Comment by haowei99** [comment]
> Also, if you can, please update the AddCourseCard modal stuff to match the regular modal.

Do you mean the height?

**Comment by CalderLund** [comment]
> > Also, if you can, please update the AddCourseCard modal stuff to match the regular modal.
> 
> Do you mean the height?

I mean the problem discussed in today's meeting.

**Review by CalderLund — DISMISSED** [review]
lgtm

**Comment by haowei99** [comment]
lgtm

**Review by haowei99 — APPROVED** [review]

**Pull request merged**
